import {StyleSheet} from 'react-native';
import {graybg, primary, secondary} from '../../../style';
import { responsiveFontSize, responsiveHeight } from 'react-native-responsive-dimensions';

export const styles = StyleSheet.create({
  root: {
    backgroundColor: '#111',
    //flex: 1,
  },
  exvw: {
    height: '100%',
    backgroundColor: '#111',
    position: 'relative',
  },
  rm_main:{
    backgroundColor:'#111111',
    paddingHorizontal:14,
    paddingVertical:18,
    // height: '100%',
},
hdtxt:{
    color:'#fff',
    fontSize:16,
    fontFamily:'Poppins-SemiBold',
    marginBottom:14,
},
tmtle:{
    marginBottom:16,
    textAlign:'center',
},
scoreText:{
    textAlign:'center',  
    color:'#fff',
    fontSize:16,
    fontFamily:'Poppins-SemiBold',
},
scoreMainContainer:{
    display: 'flex', 
    flexDirection: 'row',  
    marginTop: 10,
    marginBottom : 60
}, 
scoreSubMain1:{
    backgroundColor: secondary, 
    display: 'flex', 
    flex: 1, 
    borderRadius: 30, 
    justifyContent: 'center', 
    marginRight: 5, 
    padding: 5 
},
scoreSubMain2:{
    backgroundColor: 'orange', 
    display: 'flex', 
    flex: 1, 
    borderRadius: 30, 
    justifyContent: 'center', 
    marginLeft: 5, 
    padding: 5 
},
tmplym:{
    flexDirection:'row',
    alignItems:'flex-start',
    justifyContent:'space-between',
    marginBottom:10,
},
tmnlft:{
    flexDirection:'row',
    flexBasis:'49%',
},
tmnlfttn:{
    backgroundColor:'#242424',
    paddingHorizontal:10,
    paddingVertical:3,
    marginRight:10,
    borderRadius:10,
    color:primary,
    fontSize:9,
    fontFamily:'Poppins-Medium',
    flexBasis:'34%',
    textAlign:'center',
},
mainplyrs:{
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'flex-start',
    width:'100%',
},
indmain:{
    flexDirection:'row',
    justifyContent:'space-between',
    flexWrap:'wrap',
},
tma:{
    flexBasis:'49%',
},
tmplyrlft:{
    flexBasis:'49%',
    paddingVertical:10,
    paddingHorizontal:10,
    backgroundColor:'#383838',
    borderRadius:12,
    flexDirection:'row',
    marginBottom:7,
    borderTopWidth:3,
    borderTopColor:'#279bff',
    borderStyle:'solid',
    height:88,
},
tmplyrlft2:{
    flexBasis:'100%',
},
bdnn:{
    borderTopWidth:0,
},
plyrlft:{
    flexBasis:'34%',
    marginRight:10,
},
plyrprfl:{
    width:33,
    height:33,
    borderRadius:70,
    alignItems:'center',
    justifyContent:'center',
    borderWidth:2,
    borderColor:'#2d2d2d',
    borderStyle:'solid',
    overflow:'hidden',
    marginRight:5,
},
headerContainer: {
    backgroundColor: '#111111',
    // marginBottom: 130,
  },
  countryBox: {
    paddingVertical: 10,
    backgroundColor: '#383838',
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 7,
  },
  countryBoxTopHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderColor: '#404040',
    borderStyle: 'dotted',
    marginBottom: 4,
  },
  teamLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flexBasis: '30%',
  },
  teamsImage: {
    width: 28,
    height: 28,
    borderRadius: 100,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  teamLeftNameText: {
    fontSize: 11,
    color: '#fff',
    fontFamily: 'Poppins-Medium',
    textAlign: 'left',
  },
  teamsImageStyle: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  teamName: {
    flexDirection: 'row',
    flexBasis: '70%',
  },
  timerBox: {
    width: 74,
    backgroundColor: '#fff',
    borderRadius: 30,
    marginLeft: 'auto',
    marginRight: 'auto',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  timerText: {
    textAlign: 'center',
    color: '#279bff',
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
  },
  timerTextOrange: {
    textAlign: 'center',
    color: '#e79013',
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
  },
  teamRight: {
    alignItems: 'center',
    flexBasis: '30%',
    flexDirection: 'row-reverse',
  },
  teamRightImage: {
    width: 28,
    height: 28,
    borderRadius: 100,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 0,
    marginLeft: 7,
  },
  teamRightTextContainer: {
    flexDirection: 'row',
    flexBasis: '70%',
    justifyContent: 'flex-end',
  },
  playerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
  },

  playerContentBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    flexBasis: '49%',
  },
  plyrlft: {
    flexBasis: '34%',
    marginRight: 10,
  },
  plyrruns: {
    fontSize: 10,
    textAlign: 'left',
    marginBottom: 3,
  },
  cvctxt: {
    position: 'absolute',
    top: responsiveHeight(6),
    right: 15,
    backgroundColor: secondary,
    color: '#fff',
    fontSize: responsiveFontSize(1.2),
    fontFamily: 'Poppins-Medium',
    width: 22,
    height: 22,
    borderRadius: 30,
    textAlign: 'center',
    alignItems: 'flex-end',
    justifyContent: 'center',
    lineHeight: 18,
  },
  plyrrank: {
    backgroundColor: '#2d2d2d',
    paddingHorizontal: 0,
    paddingVertical: 2,
    borderRadius: 12,
    textAlign: 'center',
    fontSize: 8,
    maxWidth: 60,
  },
  adplyr: {
    width: 16,
    height: 16,
    borderRadius: 50,
    backgroundColor: '#5a5a5a',
    position: 'absolute',
    right: 5,
    bottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adplusimg: {
    width: 10,
    height: 10,
  },
  ortxt: {
    color: '#fff',
    fontSize: 9,
    fontFamily: 'Poppins-Medium',
  },
  plyrtm: {
    backgroundColor: '#2d2d2d',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 14,
    width: 35,
    textAlign: 'center',
  },
  plyrsd: {
    fontSize: 7,
    width: 47,
  },
  dotp: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    width: '100%',
  },
  dotimg: {
    width: 2,
    height: 65,
    resizeMode: 'contain',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  dotp2: {
    width: '70%',
    top: '7%',
  },
  plyrname: {
    marginBottom: 3,
  },
  pteam: {
    width: 50,
    height: 50,
  },
  pmtch: {
    paddingVertical: 0,
    marginBottom: 16,
  },
  tmtxt: {
    fontSize: 13,
  },
  team: {
    flexBasis: 40,
    alignItems: 'center',
  },
  mtchtm: {
    flexBasis: 120,
  },
  teamvw: {
    width: 30,
    height: 30,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: '#4c4c4c',
    overflow: 'hidden',
    marginBottom: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tmimg: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  plyrlftprfl: {
    marginRight: 0,
    marginBottom: 4,
    width: 32,
    height: 32,
  },
  tmname: {
    marginBottom: 0,
    textAlign: 'left',
  },
  wnrtxt :{
    marginRight:60,
  },
  tmtletl: {
    textAlign: 'left',
  },
  teamnm: {
    fontSize: 11,
    color: '#fff',
    fontFamily: 'Poppins-Medium',
    flex:1
  },
  borderTopBlueWidth: {
    borderTopWidth: 3,
    borderTopColor: secondary,
  },
  borderTopOrangeWidth: {
    borderTopWidth: 3,
    borderTopColor: 'orange',
  },
  scoreLive: {
    marginBottom:65,
    borderWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems:'center',
    borderRadius: 8,
    borderColor:'#2d2d2d',
    borderStyle:'solid',
    paddingHorizontal: 15,
    paddingVertical:2,
  },
  scoreMatch : {
    flexDirection: 'row',
    alignItems:'center',
  },
  scoreTxt :{
    fontSize: 12,
    color: '#fff',
    fontFamily: 'Poppins-Medium',
    paddingLeft:15,
  },
  ppscs: {
    width: '100%',
    height : 500,
    backgroundColor: graybg,
    borderRadius: 14,
    borderBottomEndRadius:0,
    borderBottomLeftRadius:0,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginLeft: 'auto',
    marginRight: 'auto',
    // marginTop:100,
    position:'absolute',
    bottom:40,
  },
  crtimg: {
    width: 40,
    height: 40,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  tmsdimg:{
    width:'100%',
    height:'100%',
    position:'relative',  
  },
  sucstxt: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: primary,
    marginBottom: 14,
    width: '60%',
    marginLeft: 'auto',
    marginRight: 'auto',
    textAlign: 'center',
  },
  okbtn: {
    borderRadius: 5,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#6a6a6a',
    paddingVertical: 8,
    width: '30%',
    marginLeft: 'auto',
    marginRight: 'auto',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontFamily: 'Poppins-Medium',
    fontSize: 10,
    color: primary,
  },
  draftOk: {
    backgroundColor : '#0096FF',
  },
  teamtab : {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth:1,
    borderColor:"#4d4d4d",
    borderRadius:30,
    height:48,
    marginRight:20,
    marginTop:20,
    marginBottom:20,
    padding:4,
    width:'100%',
  },
  scorecross : {
    width:30,
    position:'relative',
    left:'90%',
    // right:'10%',
  },
  scorearw : {
    width:30,
    marginLeft:40,
    marginTop:4,
  },
  team : {
    flexDirection: 'row',
    justifyContent:'center',
    alignItems:'center',
    width:'50%',
   //  padding:10,
    height:38,
    borderRadius:30,
    textAlign:'center',
   },
   teamTitle : {
    color :'#fff',
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    color: '#fff',
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  teamviw : {
    backgroundColor : '#494949',
    borderRadius:15,
  },
  teamLive : {
    paddingHorizontal:20,
    paddingTop:10,
    padddingBottom:20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  tmsdimg : {
    width:30,
    height:30,
    borderRadius:50,
  },
  temInfo : {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  temtxt : {
    // paddingRight:10,
    display:'flex',
    alignItems: 'center',
  },
  temcnt : {
    paddingTop:5,
    textAlign:'center',
    color: '#fff',
    fontSize:10,
  },
  temnum : {
    color: '#fff',
    fontSize:12, 
    fontFamily: 'Poppins-SemiBold',
    paddingRight:5,
  },
  temcunt : {
    color: '#fff',
    fontSize:9, 
    fontFamily: 'Poppins-Medium',
    backgroundColor :graybg,
    padding:2,
    paddingLeft:5,
    paddingRight:5,
    borderRadius:10,
    textAlign:'center',
  },
  temBat : {
    flexDirection: 'row',
    justifyContent: 'space-between', 
    alignItems: 'center',
  },
  temyet : {
    marginRight:10,
    textAlign:'center',
    backgroundColor :graybg,
    padding:4,
    borderRadius:12,
    color: '#fff',
    fontSize:12,
  },
  temIning : {
    textAlign:'center',
    color: '#FF7F7F',
    fontSize:12,
    borderBottomWidth:0.5,
    borderBottomColor:'#fff',
    paddingBottom:10,
  },
  ctryname :{
    fontSize:12, 
    fontFamily: 'Poppins-Medium',
    backgroundColor :graybg,
    padding:2,
    paddingLeft:5,
    paddingRight:5,
    borderRadius:10,
    textAlign:'center',
    color: '#fff'
  },
  temBating : {
    paddingTop: 15,
    paddingHorizontal:20,
    marginBottom:30,
  },
  temBatxt : {
    backgroundColor :graybg,
    padding:4,
    marginBottom:30,
    borderRadius:12,
  },
  temname : {
    textAlign:'center',
    color: '#fff',
    fontSize:12,
    fontFamily: 'Poppins-Medium',
  },
  btngScore : {
    flexDirection: 'row',
    alignItems: 'center',
  },
  btrnam : {
    width:50,
    height:50,
    borderRadius:10,
    backgroundColor:'blue',
  },
  circle: {
    width: 7,
    height: 7,
    borderRadius: 10,
    backgroundColor: 'blue',
    marginRight:5,
  },
  prsnme : {
    color: '#fff',
    fontSize:14,
    fontFamily: 'Poppins-Medium', 
  },
  circle1: {
    width: 6,
    height: 6,
    borderRadius: 10,
    backgroundColor: 'blue',
    marginRight:10,
    marginBottom:17,
  },
  circle2 : {
    width: 7,
    height: 7,
    borderRadius: 10,
    backgroundColor: graybg,
    marginRight:5,
  },
  circle3: {
    width: 6,
    height: 6,
    borderRadius: 10,
    backgroundColor: graybg,
    marginRight:10,
    marginBottom:17,
  },
  score : {
    color: '#fff',
    fontSize:12,
    fontFamily: 'Poppins-Medium', 
    backgroundColor:graybg,
    paddingRight:15,
    paddingLeft:15,
    paddingTop:4,
    paddingBottom:2,
    textAlign:'center',
    borderRadius:15,
  },

  scoreCard : {
    // backgroundColor : 'grey',
    flexDirection : 'row',
    alignItems : 'center',
    justifyContent : 'space-between',
    padding : 6,
    fontSize : 10,
  },
  plyrName : {
    flex : 40,
    textAlign:'center',
  },
  scoreCardHeader : {
    color : '#fff',
    fontFamily : 'Poppins-Medium',
    backgroundColor:graybg,
    borderRadius : 11,
    padding : 6,
    fontSize : 9,
    paddingVertical:2,
    paddingLeft:9,
    paddingRight:9,
    borderBottomWidth:0.5,
    height:20, 
    overflow : 'hidden' 
  },
  scoreNo : {
    color : '#fff',
    fontFamily : 'Poppins-Medium',
    fontSize : 10,

  },
  scorelst : {
    flexDirection : 'row',
    alignItems : 'center',
    justifyContent : 'space-around',
    // paddingVertical:10,
    flex:50,


  },




















});