import {StyleSheet} from 'react-native';
import { responsiveHeight, responsiveWidth } from 'react-native-responsive-dimensions';

export const styles = StyleSheet.create({
  modelContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    bottom: 25,
  },
  trophyImageContainer: {
    height: '44%',
  },
  footerBottomContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 45,
    marginHorizontal: 16,
  },
  didnotText: {
    color: '#fff',
    fontSize: 12,
    // fontFamily:'Poppins-Medium',
  },
  btnr: {
    marginTop: 6,
    marginBottom: 22,
  },
  modal1: {
    height: 395,
  },

  loginfrom: {
    width: '100%',
    Height: 450,
    backgroundColor: '#383838',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
  },
  dash: {
    width: 80,
    height: 7,
    backgroundColor: '#757575',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 'auto',
    marginLeft: 'auto',
    marginTop: 10,
    marginBottom: 35,
    borderRadius: 5,
  },
  wlcm: {
    color: '#fff',
    // fontFamily:'Poppins-SemiBold',
    fontSize: 30,
  },
  vrwth: {
    marginTop: 10,
    color: '#fff',
    // fontFamily:'Poppins-Regular',
    fontSize: 15,
    marginBottom: 34,
  },
  resendText: {
    marginLeft: 6,
    color: '#fff',
    fontSize: 12,
    // fontFamily:'Poppins-Medium',
    position: 'relative',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    textDecorationColor: '#afafaf',
  },
  cncl: {
    color: '#fff',
    fontSize: 11,
    // fontFamily:'Poppins-Regular',
    textAlign: 'center',
    marginBottom: 36,
  },

  otpmain: {
    width: '84%',
    backgroundColor: '#383838',
    borderRadius: 13,
    paddingHorizontal: 24,
    paddingVertical: 20,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  lockImageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    marginTop: 30,
  },
  lockIcon: {
    width: 40,
    height: 48,
  },
  checkphoneText: {
    color: '#fff',
    fontSize: 15,
    // fontFamily:'Poppins-SemiBold',
    marginBottom: 3,
    textAlign: 'center',
  },

  sendCodeText: {
    color: '#fff',
    fontSize: 10,
    // fontFamily:'Poppins-Regular',
    marginBottom: 12,
    textAlign: 'center',
  },
  otpcd: {
    marginHorizontal: 0,
    marginBottom: 16,
  },
  closeIcon: {
    position: 'absolute',
    right: -10,
    top:-18,
    padding:8,
    resizeMode:'center',
    width: responsiveWidth(4),
    height: responsiveHeight(4),
    zIndex: 99,
  },
  timerText: {
    color: '#279bff',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 14,
  },
  votp: {
    marginBottom: 4,
  },
  homemain: {
    opacity: 0.5,
    position: 'absolute',
    right: 0,
    width: '100%',
    height: '100%',
  },
  getStartedContainer: {
    marginTop: 120,
    width: '90%',
    marginLeft: 'auto',
    marginRight: 'auto',
    justifyContent: 'center',
    alignItems: 'center',
  },
  getStartedContent: {
    opacity: 0.8,
    width: '100%',
    marginLeft: 'auto',
    marginRight: 'auto',
    height: 44,
    backgroundColor: '#246afe',
    borderTopWidth: 4,
    borderTopColor: '#3979ff',
    borderStyle: 'solid',
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    color: '#fff',
    // fontFamily:'Poppins-Bold',
    fontSize: 15,
    textTransform: 'uppercase',
    textAlignVertical: 'center',
    lineHeight: 40,
  },
});
