import {StyleSheet} from 'react-native';
import {graybg, primary, secondary} from '../../../style';
import {responsiveFontSize} from 'react-native-responsive-dimensions';

export const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: '#111',
    height:'100%',
    width:'100%',
  },
  root: {
    flex: 1,
  },
  exvw: {
    height: '100%',
    backgroundColor: '#111',
    position: 'relative',
  },
  ppscs: {
    width: '84%',
    backgroundColor: graybg,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  plypp: {
    width: '100%',
  },
  maincls: {
    position: 'relative',
    zIndex: 999999,
  },
  clsicon: {
    position: 'absolute',
    right: 16,
    top: 12,
    width: 12,
    height: 12,
    zIndex: 99,
  },
  pcls: {
    right: 3,
    top: 3,
  },
  plyrprflinfo: {
    flexDirection: 'row',
  },
  mplpp: {
    paddingBottom: 6,
    borderBottomColor: '#3c3c3c',
    borderBottomWidth: 1,
    borderStyle: 'solid',
  },
  plyrprfl: {
    width: 33,
    height: 33,
    borderRadius: 70,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#2d2d2d',
    borderStyle: 'solid',
    overflow: 'hidden',
    marginRight: 5,
  },
  pprfl: {
    width: 35,
    height: 35,
    borderWidth: 2,
  },
  tmsdimg: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  teamnm: {
    fontSize: responsiveFontSize(1),
    color: primary,
    fontFamily: 'Poppins-Medium',
    textAlign: 'center',
  },
  wnrtxt: {
    marginBottom: 16,
  },
  tmname: {
    marginBottom: 0,
    textAlign: 'center',
  },
  plyrname: {
    marginBottom: 3,
  },
  plnm: {
    textAlign: 'left',
  },
  ortxt: {
    color: primary,
    fontSize: 8.5,
    fontFamily: 'Poppins-Medium',
  },
  plyrtm: {
    backgroundColor: '#2d2d2d',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 14,
    textAlign: 'center',

  },
  listhd: {
    paddingVertical: 5,
    borderBottomColor: '#3c3c3c',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scrhd: {
    flexBasis: '14%',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  orhd: {
    backgroundColor: '#5a5a5a',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 30,
    fontSize: 8,
    // marginRight:'auto',
  },
  txtinfo: {
    backgroundColor: 'none',
    textAlign: 'center',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  crtimg: {
    width: 40,
    height: 40,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  sucstxt: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: primary,
    marginBottom: 14,
    width: '60%',
    marginLeft: 'auto',
    marginRight: 'auto',
    textAlign: 'center',
  },
  okbtn: {
    borderRadius: 5,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#6a6a6a',
    paddingVertical: 8,
    width: '30%',
    marginLeft: 'auto',
    marginRight: 'auto',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontFamily: 'Poppins-Medium',
    fontSize: 10,
    color: primary,
  },
  tmslcnmain: {
    backgroundColor: '#111111',
    paddingHorizontal: 14,
    paddingVertical: 18,
    marginBottom: 130,
  },
  hdtxt: {
    color: primary,
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 14,
  },
  tmtle: {
    marginBottom: 16,
    textAlign: 'center',
  },
  tmmain: {
    paddingVertical: 10,
    backgroundColor: graybg,
    borderRadius: 12,
    paddingHorizontal: 12,
  },
  tmpsmain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderColor: '#404040',
    borderStyle: 'dotted',
    marginBottom: 4,
  },
  tmlft: {
    flexDirection: 'row',
    alignItems: 'center',
    flexBasis: '50%',
  },
  tmsimg: {
    width: 28,
    height: 28,
    borderRadius: 100,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  tmrht: {
    justifyContent: 'flex-end',
  },
  prvmain: {
    width: 45,
  },
  psimg: {
    width: 25,
    height: 25,
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    borderWidth: 1,
    borderColor: primary,
    borderStyle: 'solid',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginBottom: 3,
  },
  prvtxt: {
    fontSize: 10,
  },
  sc: {
    marginLeft: 12,
  },
  nxtbtn: {
    fontSize: 13,
    fontFamily: 'Poppins-SemiBold',
    color: primary,
  },
  nxtfixbtn: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 110,
    backgroundColor: '#279bff',
    paddingVertical: 11,
    borderRadius: 8,
    marginLeft: 'auto',
    marginBottom : 300
  },
  nxtfix: {
    paddingTop: 12,
    paddingBottom: 16,
    borderTopColor: '#3d3d3d',
    borderTopWidth: 1,
    borderStyle: 'solid',
    backgroundColor: '#111',
    position: 'absolute',
    bottom: 60,
    left: 0,
    right: 0,
    paddingHorizontal: 14,
  },
  alpkd: {
    backgroundColor: '#5a5a5a',
  },
  topo: {
    backgroundColor: graybg,
    paddingHorizontal: 13,
    paddingVertical: 4,
    marginStart: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    // marginEnd :20,
  },
  hdoptns: {
    // marginRight: 'auto',
  },
  pkop: {
    backgroundColor: secondary,
    paddingHorizontal: 13,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  orngpick: {
    backgroundColor: '#e79013',
  },
  srtby: {
    // flexBasis: '20%',
  },
  rnoptn: {
    // flexBasis: '20%',
  },
  plyrmain: {
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 12,
    backgroundColor: graybg,
    marginBottom: 10,
    marginLeft: 13,
    marginRight: 13,
  },
  plyrinfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  picon: {
    width: 7,
    height: 7,
    marginRight: 5,
  },
  ptkmain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  pntlist: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    flexBasis: '68%',
  },
  pntitem: {
    width: 12,
    height: 12,
    borderRadius: 20,
    backgroundColor: '#5a5a5a',
    padding: 3,
    marginRight: 5,
    marginBottom: 5,
  },
  ppicked: {
    backgroundColor: secondary,
  },
  wtick: {
    width: '100%',
    height: '100%',
  },
  tmarmain: {
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderColor: '#171717',
    borderStyle: 'solid',
  },
  tmarlist: {
    flexDirection: 'row',
    // justifyContent: 'space-between',
    paddingRight:15,
    // width: '74%',
    // marginLeft: 'auto',
    // marginRight: 'auto',
  },
  plyrhd: {
    borderBottomWidth: 0,
  },
  plyrshd: {
    justifyContent: 'space-between',
    width: '100%',
  },
  ptmr: {
    width: 92,
    backgroundColor: primary,
    paddingHorizontal: 20,
    paddingVertical: 5,
    borderRadius: 30,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginBottom: 20,
  },
  sltm: {
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    width: 64,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  tmrtxt: {
    color: secondary,
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 0,
  },
  pktmr: {
    fontSize: 14,
  },
  cvcslct: {
    flexDirection: 'row',
    // justifyContent:'center',
  },
  cslct: {
    width: 20,
    height: 20,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 5,
  },
  ctxt: {
    color: '#2d2d2d',
    lineHeight: 12,
  },
  countryBoxTopHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent:'center',
    // paddingBottom: 12,
    // borderBottomWidth: 1,
    borderColor: '#404040',
    borderStyle: 'dotted',
    marginBottom: 4,
  },
  teamLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flexBasis: '30%',
  },
  teamsImage: {
    width: 28,
    height: 28,
    borderRadius: 100,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  teamLeftNameText: {
    fontSize: 11,
    color: '#fff',
    fontFamily: 'Poppins-Medium',
    textAlign: 'left',
  },
  teamsImageStyle: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  teamName: {
    flexDirection: 'row',
    flexBasis: '100%',
  },
  timerBox: {
    width: 74,
    backgroundColor: '#fff',
    borderRadius: 30,
    // marginLeft: 'auto',
    marginRight: 'auto',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  timerText: {
    textAlign: 'center',
    color: '#279bff',
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
  },
  timerTextOrange: {
    textAlign: 'center',
    color: '#e79013',
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
  },
  teamRight: {
    alignItems: 'center',
    flexBasis: '30%',
    flexDirection: 'row-reverse',
  },
  teamRightImage: {
    width: 28,
    height: 28,
    borderRadius: 100,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 0,
    marginLeft: 7,
  },
  teamRightTextContainer: {
    flexDirection: 'row',
    flexBasis: '70%',
    justifyContent: 'flex-end',
  },
  nxtfixbtn: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 110,
    backgroundColor: '#279bff',
    paddingVertical: 11,
    borderRadius: 8,
    marginLeft: 'auto',

  },
  countryBox : {
    backgroundColor:graybg,
    margin:10,
    borderRadius:15,
    padding:10,
  },
  headingdText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  captanTxt :{
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft :16,
    marginRight:16,
  },
  cpttxt :{
    color :'#fff',
    backgroundColor:graybg,
    borderRadius:12,
    padding:8,
    paddingTop:3,
    paddingBottom:3,
    fontSize: 10,
    fontFamily: 'Poppins-Medium',
  },
  nxtfixbtn : {
    backgroundColor: 'transparent',
    position: 'absolute',
    bottom: 80,
    right: 0,
    left: 0,
    width:'100%',
    // borderRadius:10,
    // borderTopColor: 'grey',
    // borderTopWidth: 1,
  },
  nxtbtn :{
    backgroundColor: '#279bff',
    // width:110,
    paddingRight:15,
    paddingLeft:15,
    borderRadius:10,
    paddingTop: 8,
    paddingBottom: 10,
    // paddingHorizontal: 14,
    textAlign:'center',
    color :'#fff',
    marginLeft: 'auto',
    marginRight:20,
    marginTop:20,
  },
});
