import {StyleSheet} from 'react-native';
import { ceil } from 'react-native-reanimated';
import { responsiveHeight, responsiveWidth } from 'react-native-responsive-dimensions';

export const styles = StyleSheet.create({
    textFieldContainer: {
        marginTop: 0,
      },
      labelText: {
        fontSize: 14,
        color: '#fff',
        marginBottom: 8,
      },
      labelTextHeader:{
        fontSize: 16,
        color: '#fff',
        marginBottom: 8,
        textAlign:'center',
        fontFamily: 'Poppins-Medium',
      },
      labelText:{
        fontSize: 14,
        color: '#fff',
        marginBottom: 8,
        padding: 6,
        fontFamily: 'Poppins-Medium',
      },
      textInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'black',
        borderRadius: 8,
        padding: 6,
        marginBottom: 20,
        borderWidth: 2,
        borderColor: '#4d4d4d',
      },
      prefixIconContainer: {
        marginRight: 8,
        paddingRight: 8,
        borderRightWidth: 1,
        borderColor: '#404040',
      },
      suffixIconContainer: {
        marginRight: 5,
        paddingRight: 5,
        borderRightWidth: 0,
        borderColor: '#404040',
      },
      prefixIcon: {
        width: 20,
        height: 20,
      },
      profile: {
        width: 100,
        height: 100,
        borderRadius: 100 / 2,
        overflow: "hidden",
        borderWidth: 3,
        borderColor : 'grey'
      },
      editIcon: {
        width: 30,
        height: 30,
        borderRadius: 30 / 2,
        overflow: "hidden",
        borderWidth: 3,
        alignSelf:'flex-end',
        backgroundColor:'#fff'
      },
      textField: {
        flex: 1,
        height: 40,
        color: '#fff',
      },
      errorText: {
        color: 'red',
        fontSize: 12,
        marginBottom: 8,
      },
      getStartedButtonContainer: {
        flex: 1,
        justifyContent: 'flex-end',
      },


  /////////////////// New Email ///////////////////
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
    height: 60,
    zIndex: 99999999,
    elebation: 0,
    backgroundColor: '#383838',
    inactiveBackgroundColor: 'red',
    activeTintColor: 'green',
    justifyContent: 'space-between',
    borderTopColor: '#383838',
    
},
bottomNavText: {
    color: '#fff',
    fontSize: 8,
    fontFamily: 'Poppins-Medium',
    textAlign: 'center',
    // color:focused ? 'magenta' :'green',
},
iconView: {
    width: 65,
    height: 65,
    borderRadius: 120,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#111',
    borderWidth: 2,
    borderColor: '#55575b',
    borderStyle: 'solid',
    marginBottom: 20,
},
iconImageStyle: {
    width: 20,
    height: 35,
},
historyImage: {
    position: 'relative', width: 16, height: 16, resizeMode: 'contain', marginBottom: 10,
    marginLeft: 'auto',
    marginRight: 'auto',
},
draftImage: {
    position: 'relative', width: 22, height: 18, resizeMode: 'contain', marginBottom: 10,
    marginLeft: 'auto',
    marginRight: 'auto',
},
walletImage: {
    position: 'relative', width: 18, height: 14, resizeMode: 'contain', marginBottom: 10,
    marginLeft: 'auto',
    marginRight: 'auto',
},
myGamesIcon: {
    position: 'relative', width: 12, height: 16, resizeMode: 'contain', marginBottom: 10,
    marginLeft: 'auto',
    marginRight: 'auto',
},
screenViewContainer: {
    width: 60, height: 60, alignItems: 'center', justifyContent: 'center',
},
bottomViewBottom: {
    width: 30, height: 2, marginLeft: 'auto', marginRight: 'auto', position: 'absolute', bottom: 1
}, hdleft:{
    flexDirection:'row',
},
helpi:{
    width:14,
},
ntfni:{
    width:11,
},
ntfn:{
    marginRight:0,
},
user:{
    width:25,
    height:25,
    borderRadius:50,
    backgroundColor:'#ccc',
    // overflow:'hidden',
},
userp:{
    width:'100%',
    height:'100%',
    resizeMode: 'cover',
    borderRadius:100,     
},
scrnbg:{
    backgroundColor:'#111111',
    
},
header:{
    minHeight:66,
    borderBottomColor:'#414141',
    borderBottomWidth:1,
    paddingTop:28,
    paddingBottom:12,
    paddingHorizontal:14,
    // flexDirection:'row',
    // alignItems:'end',
    // justifyContent:'space-between',
    // width:'100%',
    // position:'sticky',
    top:0,
    zIndex:999999,
    left:0,
    right:0,
},

hdlist:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
    position:'relative',
    // zIndex:999,
},
menu:{
    width:23,
    height:23,
    alignItems:'center',
    justifyContent:'center',
    borderRadius:5,
    backgroundColor:'#303030',
    marginRight:7,
},
backMenu:{
    width:23,
    height:23,
    marginRight:7,
},
menui:{
    width:15,
    height:'100%',
    resizeMode: 'contain',      
},
backIcon:{
    width:10,
    height:'100%',
    resizeMode: 'contain',      
},
adot:{
    width:6,
    height:6,
    backgroundColor:'#279bff',
    borderRadius:50,
    position:'absolute',
    right:0,
    bottom:0,
    borderColor:'#000',
    borderWidth:1,
    borderStyle:'solid',
    zIndex:999999,
},
hdmdl:{
    height:14,
    width:100,
    // position:'absolute',
    // left:0,
    // right:0,
    // zIndex:9,
    marginLeft:'auto',
    marginRight:'auto',
    textAlign:'center',
},
hlogo:{
    width:'100%',
    height:'100%',
    resizeMode: 'contain',
},

///////////////////////////OTP////////////////
modelContainer: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  bottom: 25,
},
trophyImageContainer: {
  height: '44%',
},
footerBottomContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  marginBottom: 45,
  marginHorizontal: 16,
},
didnotText: {
  color: '#fff',
  fontSize: 12,
  // fontFamily:'Poppins-Medium',
},
btnr: {
  marginTop: 6,
  marginBottom: 22,
},
modal1: {
  height: 395,
},

loginfrom: {
  width: '100%',
  Height: 450,
  backgroundColor: '#383838',
  borderTopLeftRadius: 30,
  borderTopRightRadius: 30,
  position: 'absolute',
  bottom: 0,
  left: 0,
  right: 0,
  paddingHorizontal: 20,
},
dash: {
  width: 80,
  height: 7,
  backgroundColor: '#757575',
  alignItems: 'center',
  justifyContent: 'center',
  marginRight: 'auto',
  marginLeft: 'auto',
  marginTop: 10,
  marginBottom: 35,
  borderRadius: 5,
},
wlcm: {
  color: '#fff',
  // fontFamily:'Poppins-SemiBold',
  fontSize: 30,
},
vrwth: {
  marginTop: 10,
  color: '#fff',
  // fontFamily:'Poppins-Regular',
  fontSize: 15,
  marginBottom: 34,
},
resendText: {
  marginLeft: 6,
  color: '#fff',
  fontSize: 12,
  // fontFamily:'Poppins-Medium',
  position: 'relative',
  textDecorationLine: 'underline',
  textDecorationStyle: 'solid',
  textDecorationColor: '#afafaf',
},
cncl: {
  color: '#fff',
  fontSize: 11,
  // fontFamily:'Poppins-Regular',
  textAlign: 'center',
  marginBottom: 36,
},

otpmain: {
  width: '90%',
  backgroundColor: '#383838',
  borderRadius: 13,
  paddingHorizontal: 24,
  paddingVertical: 20,
  marginLeft: 'auto',
  marginRight: 'auto',
},
lockImageContainer: {
  alignItems: 'center',
  justifyContent: 'center',
  marginBottom: 14,
  marginTop: 30,
},
lockIcon: {
  width: 40,
  height: 48,
},
checkphoneText: {
  color: '#fff',
  fontSize: 15,
  // fontFamily:'Poppins-SemiBold',
  marginBottom: 3,
  textAlign: 'center',
},

sendCodeText: {
  color: '#fff',
  fontSize: 10,
  // fontFamily:'Poppins-Regular',
  marginBottom: 12,
  textAlign: 'center',
},
otpcd: {
  marginHorizontal: 0,
  marginBottom: 16,
},
closeIcon: {
  position: 'absolute',
  right: -10,
  top:-18,
  padding:8,
  resizeMode:'center',
  width: responsiveWidth(4),
  height: responsiveHeight(4),
  zIndex: 99,
},
timerText: {
  color: '#279bff',
  fontSize: 14,
  textAlign: 'center',
  marginBottom: 14,
},
votp: {
  marginBottom: 4,
},
homemain: {
  opacity: 0.5,
  position: 'absolute',
  right: 0,
  width: '100%',
  height: '100%',
},
getStartedContainer: {
  marginTop: 120,
  width: '90%',
  marginLeft: 'auto',
  marginRight: 'auto',
  justifyContent: 'center',
  alignItems: 'center',
},
getStartedContent: {
  opacity: 0.8,
  width: '100%',
  marginLeft: 'auto',
  marginRight: 'auto',
  height: 44,
  backgroundColor: '#246afe',
  borderTopWidth: 4,
  borderTopColor: '#3979ff',
  borderStyle: 'solid',
  borderRadius: 7,
  justifyContent: 'center',
  alignItems: 'center',
  textAlign: 'center',
  color: '#fff',
  // fontFamily:'Poppins-Bold',
  fontSize: 15,
  textTransform: 'uppercase',
  textAlignVertical: 'center',
  lineHeight: 40,
},
acctvrfy: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  backgroundColor: '#383838',
  borderRadius: 8,
  padding: 6,
  height:50,
  marginTop:10,
},
adrinfo:{
  flexDirection: 'row',
  alignItems: 'center'
},
adrimg:{
  paddingRight:30,
  paddingLeft:10,
},
acctadr: {
  fontSize: 15,
  color: '#fff',
},
verytxt:{
  backgroundColor: '#279BFF',
  borderRadius: 15,
  paddingTop: 3,
  paddingBottom: 3,
  paddingLeft:4,
  paddingRight: 4,
  width: 60,
  alignItems: 'center',
},
accvryinfo: {
  // backgroundColor: 'red',
  
}
});